# https://github.com/Automattic/node-canvas/issues/1065
brew "pixman"
brew "cairo"
brew "pango"
# brew "exa"
brew "bitwarden-cli"

brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
brew "mattisg/mattisg/adblock"
brew "golang-migrate"
tap "homebrew/cask-fonts"
cask "font-meslo-lg-nerd-font"

# cask "react-native-debugger"
# cask "figma"
cask "gimp"
cask "discord"
cask "imageoptim"
cask "insomnia"
# cask "slack"
cask "visual-studio-code"
cask "cleanshot"
cask "pixelsnap"
# cask "karabiner-elements"
cask "appcleaner"
# cask "ultimaker-cura"
# cask "brave-browser"
cask "gpg-suite"
# cask "kitty"
# cask "alfred"
cask "syncthing"
cask "finicky" # cask "choosy"
cask "raycast"
