#!/bin/bash

statusbar_bg="colour235"

# Get the current path in the segment.
get_tmux_cwd() {
  local env_name=$(tmux display -p "#D")
  local env_val=$(tmux display-message -p -F "#{pane_current_path}" -t "$env_name")
  # The version below is still quite new for tmux. Uncomment this in the future :-)
  #local env_val=$(tmux show-environment "$env_name" 2>&1)

  if [[ ! $env_val =~ "unknown variable" ]]; then
    local tmux_pwd=$(echo "$env_val" | sed 's/^.*=//')
    echo "$tmux_pwd"
  fi
}

git_branch() {
  local current_pwd=$(get_tmux_cwd)
  local branch=$(git -C ${current_pwd} rev-parse --abbrev-ref HEAD)

  if [ ! -z "$branch" ]; then
    echo "#[bg=colour2]#[fg=$statusbar_bg] ${branch}"
  fi
}

version_ruby() {
  local version=$(ruby --version | awk '{ print $2 }')
  echo "#[bg=colour1]#[fg=$statusbar_bg] ruby #[bg=$statusbar_bg]#[fg=colour1] $version"
}

version_node() {
  local version=$(node --version)
  echo "#[bg=colour4]#[fg=$statusbar_bg] node #[bg=$statusbar_bg]#[fg=colour4] $version"
}

version_npm() {
  local version=$(npm --version)
  echo "#[bg=colour5]#[fg=$statusbar_bg] npm #[bg=$statusbar_bg]#[fg=colour5] $version"
}

version_yarn() {
  local version=$(yarn --version)
  echo "#[bg=colour38]#[fg=$statusbar_bg] yarn #[bg=$statusbar_bg]#[fg=colour38] $version"
}

echo "`git_branch` #[default] `version_ruby` #[default] `version_node` #[default] `version_npm` #[default] `version_yarn` "
