#!/bin/bash

version_name_fg="colour255"
version_value_bg="colour235"

version_ruby() {
  local version=$(ruby --version | awk '{ print $2 }')
  echo "#[bg=colour160]#[fg=$version_name_fg] ruby #[bg=$version_value_bg]#[fg=colour160] $version"
}

version_node() {
  local version=$(node --version)
  echo "#[bg=colour4]#[fg=$version_name_fg] node #[bg=$version_value_bg]#[fg=colour4] $version"
}

version_npm() {
  local version=$(npm --version)
  echo "#[bg=colour5]#[fg=$version_name_fg] npm #[bg=$version_value_bg]#[fg=colour5] $version"
}

echo "`version_ruby` `version_node` `version_npm` "
