#!/bin/sh

# siji icons
ICON_MUSIC='\ue0fd'
ICON_DATE='\ue01f'
ICON_CLOCK_ROUND_OUTLINED='\ue016'
ICON_RAM='\ue146'
ICON_CPU='\ue026'
ICON_ARCH='\ue00e'
ICON_PACMAN='\ue00f'
ICON_VPN='\ue10f'
ICON_WEATHER='\ue01c'

ICON_UP='\ue13b'
ICON_DOWN='\ue13c'


#- VOLUME

ICON_VOLUME_ZERO='\ue051'
ICON_VOLUME_MUTE='\ue052'
ICON_VOLUME='\ue053'
